name: 'Creating versioning'
on: [push]
jobs:
  run-build-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Executing build.sh"
        run: |
          echo "Running build.sh"
          chmod +x ./build.sh
          ./build.sh
        shell: bash
