version: '3.7'
name: 'magratheaimages'

services:

  mag_sql:
    image: mariadb
    container_name: "magratheaimages-sql"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      # - ./databases/mysql:/application
      - ./database:/home/backups
    env_file:
      - ./docker/.env
    ports:
      - 3306

  magrathea_images:
    hostname: images.magrathea.localhost.com
    container_name: "magrathea-images"
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes: 
      - ./src:/var/www/html
      - ./src/api/compress:/var/www/compress
      - ./logs:/var/www/logs
      - ./backups:/var/www/backups
      - ./medias:/var/www/medias
      - ./cache:/var/www/cache
    ports:
      - 8081:80
      - 443
    env_file:
      - ./docker/.env

# helper containers:
  # magrathea_phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   container_name: magrathea-dev_pma
  #   environment:
  #     PMA_HOST: mag_sql
  #     PMA_PORT: 3306
  #     PMA_ARBITRARY: 1
  #   depends_on:
  #     - mag_sql
  #   ports:
  #     - 8183:80
