[errors]
	400 = "Invalid Data"
	4001 = "Incorrect upload data"
	4002 = "File Size greater than accepted"
	4003 = "File too big for this upload!"
	4004 = "Image must be requested by UUID"
	4005 = "Private key is required"
	4006 = "Invalid URL for upload"
	4007 = "Private key and image id are required"
	4008 = "Folder cannot be empty"
	401 = "Unauthorized"
	4011 = "Wrong Private Secret"
	403 = "Forbidden"
	4031 = "Private Secret Corrupted"
	4032 = "Key does not match image"
	4033 = "Usage limit reached"
	4034 = "Key expired"
	4035 = "Key not active"
	404 = "not found"
	4041 = "Public Key not found"
	4042 = "Private key not found"
	4043 = "Image not found"
	4044 = "Api key not found"
	415 = "Unsupported Media Type"
	4151 = "Invalid image extension"
	4152 = "Invalid image type"
	4153 = "Could not read image dimensions; file may be corrupt"
	500 = "Server Error"
	5001 = "Error on Internal API Request"
	5002 = "Incorrect configuration"
	5003 = "Permissions failed on server"
	5004 = "Image generation failed"
	5005 = "Could not open file"
