<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-10-25 11:35:25]

namespace MagratheaImages3\Apikey\Base;

use Magrathea2\MagratheaModelControl;

class ApikeyControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaImages3\Apikey";
	protected static $modelName = "Apikey";
	protected static $dbTable = "apikey";
}
