<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2025-12-27 03:46:05]

namespace MagratheaImages3\Images\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class ImagesBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $filename, $extension, $folder, $subfolder, $width, $height, $file_type, $size, $upload_key;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct(  $id=0  ){ 
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "images";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["filename"] = "string";
		$this->dbValues["extension"] = "string";
		$this->dbValues["folder"] = "string";
		$this->dbValues["subfolder"] = "string";
		$this->dbValues["width"] = "int";
		$this->dbValues["height"] = "int";
		$this->dbValues["file_type"] = "string";
		$this->dbValues["size"] = "int";
		$this->dbValues["upload_key"] = "string";
		$this->dbValues["created_at"] =  "datetime";
		$this->dbValues["updated_at"] =  "datetime";

		$this->relations["properties"]["Apikey"] = null;
		$this->relations["methods"]["Apikey"] = "GetApikey";
		$this->relations["lazyload"]["Apikey"] = "true";
		$this->relations["external"]["upload_key"] = "\MagratheaImages3\Apikey\Apikey";

	}

	public function GetControl() {
		return new \MagratheaImages3\Images\Base\ImagesControlBase();
	}

	// >>> relations:
	public function GetApikey(){
		if($this->relations["properties"]["Apikey"] != null) return $this->relations["properties"]["Apikey"];
		$this->relations["properties"]["Apikey"] = new \MagratheaImages3\Apikey\Apikey($this->upload_key);
		return $this->relations["properties"]["Apikey"];
	}
	public function SetApikey($apikey){
		$this->relations["properties"]["Apikey"] = $apikey;
		$this->upload_key = $apikey->GetID();
		return $this;
	}

}
