<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2023-10-25 12:01:57]

namespace MagratheaImages3\Images\Base;

use Magrathea2\MagratheaModelControl;

class ImagesControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaImages3\Images";
	protected static $modelName = "Images";
	protected static $dbTable = "images";
}
