name: 'Creating versioning'
on: [push]
jobs:
  run-build-sh:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Executing build.sh"
        run: |
          echo "Running build.sh"
          chmod +x ./build.sh
          ./build.sh
        shell: bash
      - name: Commit files
        run: |
          git add src/configs/git_info.txt
          git add src/configs/version.php
          git commit -m "github actions run-build-sh"
          git push
